// Auto-generated database types from Supabase
// This file will be generated by: npm run generate:types
export type Database = {
  public: {
    Tables: {};
    Views: {};
    Functions: {};
  };
};
